apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b1wevawm7-dotnet-basic
  janus-idp.io/tekton: b1wevawm7-dotnet-basic
  backstage.io/kubernetes-id: b1wevawm7-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b1wevawm7-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
